//! LIR → C (the primary backend).

use crate::lir::*;
use std::collections::HashSet;
use std::fmt::Write;

pub fn ty_name(t: &LTy) -> String {
    match t {
        LTy::I64 => "I64".into(),
        LTy::IntK(k) => k.name().into(),
        LTy::F64 => "F64".into(),
        LTy::PInt => "PInt".into(),
        LTy::Bool => "Bool".into(),
        LTy::Str => "Str".into(),
        LTy::Unit => "Unit".into(),
        LTy::Arr(t) => format!("Arr_{}", ty_name(t)),
        LTy::Tup(ts) => format!("Tup_{}", ts.iter().map(ty_name).collect::<Vec<_>>().join("_")),
        LTy::Range => "Range".into(),
        LTy::Gen(t) => format!("Gen_{}", ty_name(t)),
    }
}

pub fn cty(t: &LTy) -> String {
    match t {
        LTy::I64 | LTy::IntK(_) => "int64_t".into(),
        LTy::F64 => "double".into(),
        LTy::PInt => "AlxPInt".into(),
        LTy::Bool => "bool".into(),
        LTy::Str => "AlxStr".into(),
        LTy::Unit => "int8_t".into(),
        LTy::Arr(_) | LTy::Tup(_) => ty_name(t),
        LTy::Range => "AlxRange".into(),
        LTy::Gen(_) => "AlxGen *".into(),
    }
}

/// The C type in memory (array elements, struct fields): integers take
/// their own width there; in registers they are all int64_t.
pub fn cty_mem(t: &LTy) -> String {
    match t {
        LTy::IntK(k) => match k {
            IntKind::I8 => "int8_t",
            IntKind::I16 => "int16_t",
            IntKind::I32 => "int32_t",
            IntKind::U8 => "uint8_t",
            IntKind::U16 => "uint16_t",
            IntKind::U32 => "uint32_t",
            IntKind::I64 | IntKind::U64 => "int64_t",
        }
        .into(),
        t => cty(t),
    }
}

fn zero(t: &LTy) -> String {
    match t {
        LTy::I64 | LTy::IntK(_) | LTy::Unit => "0".into(),
        LTy::F64 => "0.0".into(),
        LTy::Bool => "false".into(),
        LTy::Gen(_) => "NULL".into(),
        t => format!("({}){{0}}", cty(t)),
    }
}

const BUILTIN_ARRS: [&str; 4] = ["Arr_I64", "Arr_Str", "Arr_PInt", "Arr_Bool"];

struct Gen<'a> {
    out: String,
    types_done: HashSet<String>,
    typedefs: String,
    p: &'a LProgram,
}

pub fn emit(p: &LProgram) -> String {
    let mut g = Gen { out: String::new(), types_done: HashSet::new(), typedefs: String::new(), p };
    // Collect every type used.
    let all_funcs: Vec<&LFunc> = p.funcs.iter().chain(p.gens.iter().map(|x| &x.func)).chain(p.workers.iter().map(|w| &w.func)).collect();
    for f in &all_funcs {
        for v in &f.vars {
            g.need_type(&v.ty);
        }
        g.need_type(&f.ret);
    }
    for gn in &p.gens {
        g.need_type(&gn.elem);
    }
    // Prototypes.
    let mut protos = String::new();
    for f in &p.funcs {
        let _ = writeln!(protos, "{};", proto(f));
    }
    for gn in &p.gens {
        let caps: Vec<String> = gn.captures.iter().map(|v| format!("{} c{v}", cty(&gn.func.vars[*v].ty))).collect();
        let _ = writeln!(protos, "static AlxGen *gen{}_new({});", gn.id, if caps.is_empty() { "void".into() } else { caps.join(", ") });
    }
    for w in &p.workers {
        let _ = writeln!(protos, "static void worker{}(const void *in_, void *out_);", w.id);
    }
    // Bodies.
    for gn in &p.gens {
        g.generator(gn);
    }
    for w in &p.workers {
        g.worker(w);
    }
    for f in &p.funcs {
        if !f.external {
            g.func(f);
        }
    }
    let main = p.funcs.iter().find(|f| f.is_main).map(|f| f.name.clone()).unwrap_or_default();
    let mut s = String::new();
    s.push_str("/* Generated by alx. */\n#include \"alx.h\"\n\n");
    s.push_str(&g.typedefs);
    s.push('\n');
    s.push_str(&protos);
    s.push('\n');
    s.push_str(&g.out);
    if !main.is_empty() {
        let _ = writeln!(s, "int main(void) {{\n    alx_init();\n    {main}();\n    fflush(stdout);\n    return 0;\n}}");
    }
    s
}

fn proto(f: &LFunc) -> String {
    let params: Vec<String> = f.params.iter().map(|v| format!("{} {}", cty(&f.vars[*v].ty), vname(f, *v))).collect();
    let linkage = if f.external || f.name.starts_with("alx_lib_") { "" } else { "static " };
    if f.is_main {
        return format!("static void {}(void)", f.name);
    }
    let ret = if f.ret == LTy::Unit { "void".to_string() } else { cty(&f.ret) };
    format!("{linkage}{ret} {}({})", f.name, if params.is_empty() { "void".into() } else { params.join(", ") })
}

fn vname(f: &LFunc, v: V) -> String {
    format!("v{v}_{}", f.vars[v].name)
}

fn c_str(s: &str) -> String {
    let mut o = String::from("\"");
    for b in s.bytes() {
        match b {
            b'"' => o.push_str("\\\""),
            b'\\' => o.push_str("\\\\"),
            b'\n' => o.push_str("\\n"),
            b'\t' => o.push_str("\\t"),
            0x20..=0x7e => o.push(b as char),
            _ => {
                let _ = write!(o, "\\{b:03o}");
            }
        }
    }
    o.push('"');
    o
}

/// How the current function returns errors / values.
#[derive(Clone, Copy, PartialEq)]
enum Ctx {
    Plain,
    Main,
    Gen,
    Worker,
}

struct FnEmit<'f> {
    f: &'f LFunc,
    ctx: Ctx,
    /// In a generator: variables are fields of `g`.
    in_gen: bool,
    yields: usize,
    out: String,
    ind: usize,
}

impl Gen<'_> {
    fn need_type(&mut self, t: &LTy) {
        match t {
            LTy::Arr(inner) => {
                self.need_type(inner);
                let n = ty_name(t);
                if !BUILTIN_ARRS.contains(&n.as_str()) && self.types_done.insert(n.clone()) {
                    let _ = writeln!(self.typedefs, "ALX_ARR({}, {n})", cty_mem(inner));
                }
            }
            LTy::Tup(ts) => {
                for x in ts {
                    self.need_type(x);
                }
                let n = ty_name(t);
                if self.types_done.insert(n.clone()) {
                    let fields: Vec<String> = ts.iter().enumerate().map(|(i, x)| format!("{} f{i};", cty_mem(x))).collect();
                    let _ = writeln!(self.typedefs, "typedef struct {{ {} }} {n};", fields.join(" "));
                }
            }
            LTy::Gen(inner) => self.need_type(inner),
            _ => {}
        }
    }

    fn func(&mut self, f: &LFunc) {
        let ctx = if f.is_main {
            Ctx::Main
        } else {
            Ctx::Plain
        };
        let mut e = FnEmit { f, ctx, in_gen: false, yields: 0, out: String::new(), ind: 1 };
        let _ = writeln!(self.out, "{} {{", proto(f));
        for (i, v) in f.vars.iter().enumerate() {
            if !f.params.contains(&i) {
                let _ = writeln!(e.out, "    {} {} = {};", cty(&v.ty), vname(f, i), zero(&v.ty));
            }
        }
        e.block(&f.body);
        if f.ret != LTy::Unit && !matches!(f.body.last(), Some(LS::Return(_))) {
            let _ = writeln!(e.out, "    alx_panic(\"function ended without a value\", \"{}\");", f.name);
        }
        self.out.push_str(&e.out);
        self.out.push_str("}\n\n");
    }

    fn worker(&mut self, w: &LWorker) {
        let f = &w.func;
        let mut e = FnEmit { f, ctx: Ctx::Worker, in_gen: false, yields: 0, out: String::new(), ind: 1 };
        let _ = writeln!(self.out, "static void worker{}(const void *in_, void *out_) {{", w.id);
        for (i, v) in f.vars.iter().enumerate() {
            if f.params.contains(&i) {
                let _ = writeln!(e.out, "    {} {} = *(const {} *)in_;", cty(&v.ty), vname(f, i), cty_mem(&v.ty));
            } else {
                let _ = writeln!(e.out, "    {} {} = {};", cty(&v.ty), vname(f, i), zero(&v.ty));
            }
        }
        e.block(&f.body);
        self.out.push_str(&e.out);
        self.out.push_str("}\n\n");
    }

    fn generator(&mut self, gn: &LGen) {
        let f = &gn.func;
        let id = gn.id;
        let _ = writeln!(self.out, "typedef struct {{\n    AlxGen base;\n    int state;");
        for (i, v) in f.vars.iter().enumerate() {
            let _ = writeln!(self.out, "    {} {};", cty(&v.ty), vname(f, i));
        }
        let _ = writeln!(self.out, "}} Gen{id};\n");
        let mut e = FnEmit { f, ctx: Ctx::Gen, in_gen: true, yields: 0, out: String::new(), ind: 1 };
        e.block(&f.body);
        let n = e.yields;
        let elem = cty(&gn.elem);
        let _ = writeln!(self.out, "static bool gen{id}_next(AlxGen *g_, void *out_) {{\n    Gen{id} *g = (Gen{id} *)g_;\n    {elem} *out = out_;\n    (void)out;\n    switch (g->state) {{\n    case 0: goto start;");
        for k in 1..=n {
            let _ = writeln!(self.out, "    case {k}: goto y{k};");
        }
        let _ = writeln!(self.out, "    default: return false;\n    }}\nstart:;");
        self.out.push_str(&e.out);
        let _ = writeln!(self.out, "    g->state = -1;\n    return false;\n}}\n");
        let caps: Vec<String> = gn.captures.iter().map(|v| format!("{} c{v}", cty(&f.vars[*v].ty))).collect();
        let _ = writeln!(self.out, "static AlxGen *gen{id}_new({}) {{\n    Gen{id} *g = alx_alloc(sizeof *g);\n    memset(g, 0, sizeof *g);\n    g->base.next = gen{id}_next;", if caps.is_empty() { "void".into() } else { caps.join(", ") });
        for v in &gn.captures {
            let _ = writeln!(self.out, "    g->{} = c{v};", vname(f, *v));
        }
        let _ = writeln!(self.out, "    return &g->base;\n}}\n");
        let _ = self.p;
    }
}

impl FnEmit<'_> {
    fn line(&mut self, s: &str) {
        for _ in 0..self.ind {
            self.out.push_str("    ");
        }
        self.out.push_str(s);
        self.out.push('\n');
    }

    fn v(&self, v: V) -> String {
        if self.in_gen { format!("g->{}", vname(self.f, v)) } else { vname(self.f, v) }
    }

    fn block(&mut self, ss: &[LS]) {
        for s in ss {
            self.stmt(s);
        }
    }

    fn stmt(&mut self, s: &LS) {
        match s {
            LS::Set(v, e) => {
                let x = self.e(e);
                let v = self.v(*v);
                self.line(&format!("{v} = {x};"));
            }
            LS::SetIndex { arr, idx, val, check } => {
                let (a, i, x) = (self.v(*arr), self.e(idx), self.e(val));
                match check {
                    Some(loc) => self.line(&format!("ALX_IDX_SET({a}, {i}, {}) = {x};", c_str(loc))),
                    None => self.line(&format!("{a}.ptr[{i}] = {x};")),
                }
            }
            LS::SetPlace { var, steps, val } => {
                let mut lv = self.v(*var);
                for st in steps {
                    lv = match st {
                        Step::Index(i, Some(loc)) => format!("ALX_IDX_SET({lv}, {}, {})", self.e(i), c_str(loc)),
                        Step::Index(i, None) => format!("({lv}).ptr[{}]", self.e(i)),
                        Step::Field(k) => format!("({lv}).f{k}"),
                    };
                }
                let x = self.e(val);
                self.line(&format!("{lv} = {x};"));
            }
            LS::Push(v, e) => {
                let ty = ty_name(&self.f.vars[*v].ty);
                let x = self.e(e);
                let v = self.v(*v);
                self.line(&format!("{ty}_push(&{v}, {x});"));
            }
            LS::Eval(e) => {
                let x = self.e(e);
                self.line(&format!("(void)({x});"));
            }
            LS::If(c, a, b) => {
                let c = self.e(c);
                self.line(&format!("if ({c}) {{"));
                self.ind += 1;
                self.block(a);
                self.ind -= 1;
                if b.is_empty() {
                    self.line("}");
                } else {
                    self.line("} else {");
                    self.ind += 1;
                    self.block(b);
                    self.ind -= 1;
                    self.line("}");
                }
            }
            LS::Loop(l, body) => {
                self.line("for (;;) {");
                self.ind += 1;
                self.block(body);
                self.line(&format!("cont_{l}:;"));
                self.ind -= 1;
                self.line("}");
                self.line(&format!("brk_{l}:;"));
            }
            LS::Break(l) => self.line(&format!("goto brk_{l};")),
            LS::Continue(l) => self.line(&format!("goto cont_{l};")),
            LS::Return(v) => match (self.ctx, v) {
                (Ctx::Worker, Some(v)) => {
                    let x = self.e(v);
                    let t = cty_mem(&self.f.ret);
                    self.line(&format!("{{ *({t} *)out_ = {x}; return; }}"));
                }
                (Ctx::Plain, Some(v)) => {
                    let x = self.e(v);
                    self.line(&format!("return {x};"));
                }
                (Ctx::Gen, _) => self.line("{ g->state = -1; return false; }"),
                _ => self.line("return;"),
            },
            LS::NextOrBreak { source, dst, label } => {
                let (g, d) = (self.e(source), self.v(*dst));
                self.line(&format!("if (!({g})->next(({g}), &{d})) goto brk_{label};"));
            }
            LS::Yield(e) => {
                self.yields += 1;
                let k = self.yields;
                let x = self.e(e);
                self.line(&format!("*out = {x};"));
                self.line(&format!("g->state = {k};"));
                self.line("return true;");
                self.out.push_str(&format!("y{k}:;\n"));
            }
            LS::Pmap { dst, arr, worker } => {
                let d = self.v(*dst);
                let dt = self.f.vars[*dst].ty.clone();
                let LTy::Arr(out_t) = &dt else { unreachable!() };
                let a = self.e(arr);
                self.line("{");
                self.ind += 1;
                self.line(&format!("__typeof__({a}) in_ = {a};"));
                self.line(&format!("{d} = {}_cap(in_.len);", ty_name(&dt)));
                self.line(&format!("{d}.len = in_.len;"));
                self.line(&format!("alx_pmap(in_.ptr, in_.len, sizeof *in_.ptr, {d}.ptr, sizeof({}), worker{worker});", cty_mem(out_t)));
                self.ind -= 1;
                self.line("}");
            }
            LS::Puts(e, t) => {
                let x = self.e(e);
                let f = match t {
                    LTy::I64 => "alx_puts_i64",
                    LTy::IntK(IntKind::U64) => "alx_puts_u64",
                    LTy::IntK(_) => "alx_puts_i64",
                    LTy::F64 => "alx_puts_f64",
                    LTy::Str => "alx_puts_str",
                    LTy::Bool => "alx_puts_bool",
                    LTy::PInt => "alx_puts_pint",
                    LTy::Unit => {
                        self.line(&format!("(void)({x}); puts(\"\");"));
                        return;
                    }
                    _ => {
                        self.line(&format!("(void)({x}); alx_panic(\"`puts` of this type isn't supported yet\", \"puts\");"));
                        return;
                    }
                };
                self.line(&format!("{f}({x});"));
            }
            LS::Die(e) => {
                let x = self.e(e);
                self.line(&format!("alx_die_str({x});"));
            }
            LS::Panic(msg, loc) => self.line(&format!("alx_panic({}, {});", c_str(msg), c_str(loc))),
            LS::SortInPlace(v, el) => {
                let f = match el {
                    LTy::I64 => "alx_sort_i64",
                    LTy::Str => "alx_sort_str",
                    _ => {
                        self.line("alx_panic(\"`sort` of this element type isn't supported yet\", \"sort\");");
                        return;
                    }
                };
                let v = self.v(*v);
                self.line(&format!("{f}(&{v});"));
            }
        }
    }

    fn e(&self, e: &LE) -> String {
        match e {
            LE::Var(v) => self.v(*v),
            LE::I(i) => {
                if *i == i64::MIN {
                    "INT64_MIN".into()
                } else {
                    format!("INT64_C({i})")
                }
            }
            LE::F(v) => c_double(*v),
            LE::FArith(op, a, b) => {
                let sym = match op {
                    Op::Add => "+",
                    Op::Sub => "-",
                    Op::Mul => "*",
                    _ => "/",
                };
                format!("({} {sym} {})", self.e(a), self.e(b))
            }
            LE::FNeg(x) => format!("(-{})", self.e(x)),
            LE::Prim(p, args) => {
                let a: Vec<String> = args.iter().map(|x| self.e(x)).collect();
                let u = |x: &str| format!("((uint64_t)({x}))");
                match p {
                    Prim::And => format!("({} & {})", a[0], a[1]),
                    Prim::Or => format!("({} | {})", a[0], a[1]),
                    Prim::Xor => format!("({} ^ {})", a[0], a[1]),
                    Prim::AndNot => format!("({} & ~{})", a[0], a[1]),
                    Prim::Not => format!("(~{})", a[0]),
                    Prim::Shl => format!("((int64_t)({} << ({})))", u(&a[0]), a[1]),
                    Prim::ShrS => format!("({} >> ({}))", a[0], a[1]),
                    Prim::ShrU => format!("((int64_t)({} >> ({})))", u(&a[0]), a[1]),
                    Prim::ULt => format!("({} < {})", u(&a[0]), u(&a[1])),
                    Prim::ULe => format!("({} <= {})", u(&a[0]), u(&a[1])),
                    Prim::UDiv => format!("((int64_t)({} / {}))", u(&a[0]), u(&a[1])),
                    Prim::URem => format!("((int64_t)({} % {}))", u(&a[0]), u(&a[1])),
                    Prim::UMulHi => format!("((int64_t)(((unsigned __int128){} * {}) >> 64))", u(&a[0]), u(&a[1])),
                    Prim::Wrap(k) => format!("((int64_t)({})({}))", cty_mem(&LTy::IntK(*k)), a[0]),
                    Prim::UToF => format!("((double){})", u(&a[0])),
                }
            }
            LE::B(b) => if *b { "true" } else { "false" }.into(),
            LE::S(s) => format!("alx_str_lit({}, {})", c_str(s), s.len()),
            LE::Loc(s) => c_str(s),
            LE::Unit => "0".into(),
            LE::Tup(t, vs) => format!("(({}){{{}}})", cty(t), vs.iter().map(|x| self.e(x)).collect::<Vec<_>>().join(", ")),
            LE::Field(x, i) => format!("({}).f{i}", self.e(x)),
            LE::Arith(op, a, b, ovf) => {
                let (a, b) = (self.e(a), self.e(b));
                match ovf {
                    Ovf::Panic(loc) => {
                        let f = match op {
                            Op::Add => "alx_add",
                            Op::Sub => "alx_sub",
                            Op::Mul => "alx_mul",
                            Op::Div => "alx_div",
                            Op::Rem => "alx_rem",
                            Op::Pow => "alx_pow",
                            _ => unreachable!(),
                        };
                        format!("{f}({a}, {b}, {})", c_str(loc))
                    }
                    Ovf::Wrap => match op {
                        Op::Add => format!("alx_wadd({a}, {b})"),
                        Op::Sub => format!("alx_wsub({a}, {b})"),
                        Op::Mul => format!("alx_wmul({a}, {b})"),
                        Op::Div => format!("alx_div({a}, {b}, \"wrap\")"),
                        Op::Rem => format!("alx_rem({a}, {b}, \"wrap\")"),
                        _ => format!("alx_pow({a}, {b}, \"wrap\")"),
                    },
                    Ovf::Unchecked => match op {
                        Op::Add => format!("({a} + {b})"),
                        Op::Sub => format!("({a} - {b})"),
                        Op::Mul => format!("({a} * {b})"),
                        // Proven: divisor is a nonzero constant other than -1.
                        Op::Div => format!("alx_div({a}, {b}, \"proven\")"),
                        Op::Rem => format!("alx_rem({a}, {b}, \"proven\")"),
                        _ => format!("alx_pow({a}, {b}, \"proven\")"),
                    },
                }
            }
            LE::PArith(op, a, b) => {
                let (a, b) = (self.e(a), self.e(b));
                match op {
                    Op::Add => format!("alx_p_add({a}, {b})"),
                    Op::Sub => format!("alx_p_sub({a}, {b})"),
                    Op::Mul => format!("alx_p_mul({a}, {b})"),
                    Op::Div => format!("alx_p_div({a}, {b}, \"div\")"),
                    Op::Rem => format!("alx_p_rem({a}, {b}, \"rem\")"),
                    Op::Pow => format!("alx_p_pow({a}, {b}, \"pow\")"),
                    Op::Eq => format!("(alx_p_cmp({a}, {b}) == 0)"),
                    Op::Ne => format!("(alx_p_cmp({a}, {b}) != 0)"),
                    Op::Lt => format!("(alx_p_cmp({a}, {b}) < 0)"),
                    Op::Le => format!("(alx_p_cmp({a}, {b}) <= 0)"),
                    Op::Gt => format!("(alx_p_cmp({a}, {b}) > 0)"),
                    Op::Ge => format!("(alx_p_cmp({a}, {b}) >= 0)"),
                    _ => unreachable!(),
                }
            }
            LE::Cmp(op @ (Op::Eq | Op::Ne), a, b, LTy::Str) if palindrome_test(a, b).is_some() => {
                let x = self.e(palindrome_test(a, b).unwrap());
                let neg = if *op == Op::Ne { "!" } else { "" };
                format!("({neg}alx_str_is_pal({x}))")
            }
            LE::Cmp(op, a, b, t) => {
                let (a, b) = (self.e(a), self.e(b));
                let sym = match op {
                    Op::Eq => "==",
                    Op::Ne => "!=",
                    Op::Lt => "<",
                    Op::Le => "<=",
                    Op::Gt => ">",
                    Op::Ge => ">=",
                    Op::And => "&&",
                    Op::Or => "||",
                    _ => unreachable!(),
                };
                match t {
                    LTy::Str => match op {
                        Op::Eq => format!("alx_str_eq({a}, {b})"),
                        Op::Ne => format!("(!alx_str_eq({a}, {b}))"),
                        _ => format!("(alx_str_cmp({a}, {b}) {sym} 0)"),
                    },
                    LTy::PInt => format!("(alx_p_cmp({a}, {b}) {sym} 0)"),
                    _ => format!("({a} {sym} {b})"),
                }
            }
            LE::Neg(x, ovf) => match ovf {
                Ovf::Panic(loc) => format!("alx_neg({}, {})", self.e(x), c_str(loc)),
                _ => format!("alx_wsub(0, {})", self.e(x)),
            },
            LE::Not(x) => format!("(!{})", self.e(x)),
            LE::Cond(c, a, b) => format!("({} ? {} : {})", self.e(c), self.e(a), self.e(b)),
            LE::Call(f, args) => format!("{f}({})", args.iter().map(|x| self.e(x)).collect::<Vec<_>>().join(", ")),
            LE::Rt(rt, args) => {
                let a: Vec<String> = args.iter().map(|x| self.e(x)).collect();
                let s = |f: &str| format!("{f}({})", a.join(", "));
                match rt {
                    Rt::IntToS => s("alx_int_to_s"),
                    Rt::PIntToS => s("alx_p_to_s"),
                    Rt::StrRev => s("alx_str_rev"),
                    Rt::StrDelete => s("alx_str_delete"),
                    Rt::StrSplit => s("alx_str_split"),
                    Rt::StrToI => s("alx_str_to_i"),
                    Rt::StrChar => s("alx_str_charlen"),
                    Rt::StrByte => {
                        if a[2] == "INT64_C(0)" {
                            format!("alx_str_byte({}, {})", a[0], a[1])
                        } else {
                            s("alx_str_sub")
                        }
                    }
                    Rt::StrLen => format!("({}).len", a[0]),
                    Rt::NDigits => s("alx_int_ndigits"),
                    Rt::PNDigits => s("alx_p_ndigits"),
                    Rt::Isqrt => s("alx_isqrt"),
                    Rt::Digits => s("alx_digits"),
                    Rt::PDigits => s("alx_p_digits"),
                    Rt::SatAdd => s("alx_sat_add"),
                    Rt::ArrCopy => {
                        // The array type isn't on the expression: use typeof.
                        format!("({{ __typeof__({0}) src_ = {0}; __typeof__(src_) dst_ = src_; dst_.ptr = alx_alloc((size_t)(src_.len ? src_.len : 1) * sizeof *src_.ptr); if (src_.len) memcpy(dst_.ptr, src_.ptr, (size_t)src_.len * sizeof *src_.ptr); dst_.cap = src_.len; dst_; }})", a[0])
                    }
                    Rt::Even => s("alx_even"),
                    Rt::PEven => s("alx_p_even"),
                    Rt::PToI64 => s("alx_p_to_i64"),
                    Rt::IntToF => format!("((double)({}))", a[0]),
                    Rt::FToI => s("alx_f_to_i"),
                    Rt::FSqrt => s("sqrt"),
                    Rt::FAbs => s("fabs"),
                    Rt::FToS => s("alx_f_to_s"),
                    Rt::FFmt => s("alx_f_fmt"),
                    Rt::StrCat => format!("alx_str_cat({}, (AlxStr[]){{{}}})", a.len(), a.join(", ")),
                    Rt::U64ToS => s("alx_u64_to_s"),
                    Rt::IntFmt => s("alx_int_fmt"),
                    Rt::FToU64 => s("alx_f_to_u64"),
                    Rt::RuneToS => s("alx_rune_to_s"),
                    Rt::FileStatus => s("alx_file_status"),
                    Rt::FileRead => s("alx_file_read_or_empty"),
                    Rt::StrFromBytes => format!("alx_str_from_bytes((const uint8_t *)({0}).ptr, ({0}).len)", a[0]),
                }
            }
            LE::Index { arr, idx, check } => {
                let (a, i) = (self.e(arr), self.e(idx));
                match check {
                    Some(loc) => format!("ALX_IDX({a}, {i}, {})", c_str(loc)),
                    None => format!("({a}).ptr[{i}]"),
                }
            }
            LE::Len(x) => format!("({}).len", self.e(x)),
            LE::ArrLit(t, vs) => {
                let n = ty_name(&LTy::Arr(Box::new(t.clone())));
                if vs.is_empty() {
                    format!("{n}_cap(0)")
                } else {
                    format!("{n}_lit({}, ({}[]){{{}}})", vs.len(), cty_mem(t), vs.iter().map(|x| self.e(x)).collect::<Vec<_>>().join(", "))
                }
            }
            LE::ArrNew(t, n, fill, loc) => format!("{}_new({}, {}, {})", ty_name(&LTy::Arr(Box::new(t.clone()))), self.e(n), self.e(fill), c_str(loc)),
            LE::ArrWithCap(t, n) => format!("{}_cap({})", ty_name(&LTy::Arr(Box::new(t.clone()))), self.e(n)),
            LE::Slice(t, a, start, len) => format!("(({}){{({}).ptr + {}, {}, 0}})", ty_name(t), self.e(a), self.e(start), self.e(len)),
            LE::Range(lo, hi, ex) => format!("((AlxRange){{{}, {}, {}}})", self.e(lo), self.e(hi), ex),
            LE::RangeField(r, k) => format!("({}).{}", self.e(r), ["lo", "hi", "excl"][*k as usize]),
            LE::GenNew(id, vals) => format!("gen{id}_new({})", vals.iter().map(|x| self.e(x)).collect::<Vec<_>>().join(", ")),
            LE::ToP(x) => format!("alx_p_from({})", self.e(x)),
        }
    }
}

/// `s == s.reverse` (either side) on a variable: the variable.
pub fn palindrome_test<'a>(a: &'a LE, b: &'a LE) -> Option<&'a LE> {
    let rev_of = |x: &LE, r: &LE| matches!((x, r), (LE::Var(v), LE::Rt(Rt::StrRev, args)) if matches!(args.as_slice(), [LE::Var(w)] if w == v));
    if rev_of(a, b) {
        Some(a)
    } else if rev_of(b, a) {
        Some(b)
    } else {
        None
    }
}

/// A C double literal (the lexer can produce infinities from huge literals).
fn c_double(v: f64) -> String {
    if v.is_nan() {
        "NAN".into()
    } else if v.is_infinite() {
        if v > 0.0 { "INFINITY".into() } else { "(-INFINITY)".into() }
    } else {
        // Debug is the shortest round-trip form, always with `.` or `e`.
        format!("({v:?})")
    }
}
