//! LIR → Rust: the oracle backend. The output is checked (and can be run)
//! with rustc; if rustc rejects a program our checker accepted, our checker
//! has a bug (DESIGN.md, Architecture).

use crate::lir::*;
use std::fmt::Write;

const PRELUDE: &str = include_str!("../runtime/prelude.rs");

thread_local! {
    /// Tuples wider than Rust's 12 (no `Clone`/`Default` impls): emitted as
    /// tuple structs `Wide{n}`, by field types.
    static WIDE: std::cell::RefCell<Vec<String>> = const { std::cell::RefCell::new(vec![]) };
}

/// The tuple struct standing in for a wide tuple of these field types.
fn wide(fields: String) -> String {
    WIDE.with(|w| {
        let mut w = w.borrow_mut();
        let k = w.iter().position(|f| *f == fields).unwrap_or_else(|| {
            w.push(fields);
            w.len() - 1
        });
        format!("Wide{k}")
    })
}

fn rty(t: &LTy) -> String {
    match t {
        LTy::Tup(ts) if ts.len() > 12 => wide(ts.iter().map(rty).collect::<Vec<_>>().join(", ")),
        LTy::Region => "()".into(),
        LTy::Task(t) => format!("Task<{}>", rty(t)),
        LTy::Chan(t) => format!("Chan<{}>", rty(t)),
        LTy::Lock => "AlxLock".into(),
        LTy::Atomic => "AlxAtomic".into(),
        // Every integer kind is an i64 here (bit pattern for U64): the
        // oracle checks meaning, not memory layout.
        LTy::I64 | LTy::IntK(_) => "i64".into(),
        LTy::F64 => "f64".into(),
        LTy::PInt => "PInt".into(),
        LTy::Bool => "bool".into(),
        LTy::Str => "Str".into(),
        LTy::Unit => "()".into(),
        LTy::Arr(t) => format!("Sl<{}>", rty(t)),
        LTy::Tup(ts) if ts.is_empty() => "()".into(),
        LTy::Tup(ts) => format!("({},)", ts.iter().map(rty).collect::<Vec<_>>().join(", ")),
        LTy::Range => "AlxRange".into(),
        LTy::Gen(t) => format!("Gen<{}>", rty(t)),
    }
}

fn is_copy(t: &LTy) -> bool {
    matches!(t, LTy::I64 | LTy::IntK(_) | LTy::F64 | LTy::Bool | LTy::Unit | LTy::Range)
}

fn lit(s: &str) -> String {
    let mut o = String::from("b\"");
    for b in s.bytes() {
        match b {
            b'"' => o.push_str("\\\""),
            b'\\' => o.push_str("\\\\"),
            b'\n' => o.push_str("\\n"),
            0x20..=0x7e => o.push(b as char),
            _ => {
                let _ = write!(o, "\\x{b:02x}");
            }
        }
    }
    o.push('"');
    o
}

fn loc(s: &str) -> String {
    format!("{s:?}")
}

#[derive(Clone, Copy, PartialEq)]
enum Ctx {
    Plain,
    Main,
    Gen,
    Worker,
}

pub fn emit(p: &LProgram) -> String {
    WIDE.with(|w| w.borrow_mut().clear());
    let out = emit_inner(p);
    // The wide tuples met while emitting (a type may name another: loop).
    let mut defs = String::new();
    let mut k = 0;
    while let Some(fields) = WIDE.with(|w| w.borrow().get(k).cloned()) {
        let _ = writeln!(defs, "#[derive(Clone, Default)]\nstruct Wide{k}({fields});");
        k += 1;
    }
    out.replacen("\n// ---- generated by alx ----\n", &format!("\n// ---- generated by alx ----\n{defs}"), 1)
}

fn emit_inner(p: &LProgram) -> String {
    let mut out = String::from(PRELUDE);
    out.push_str("\n// ---- generated by alx ----\n\n");
    out.push_str(&ffi_fns(p));
    for (k, t) in p.globals.iter().enumerate() {
        let _ = writeln!(out, "static G{k}: std::sync::OnceLock<{}> = std::sync::OnceLock::new();", rty(t));
    }
    for g in &p.gens {
        let f = &g.func;
        let caps: Vec<String> = g.captures.iter().map(|v| format!("c{v}: {}", rty(&f.vars[*v].ty))).collect();
        let _ = writeln!(out, "fn gen_new_{}({}) -> Gen<{}> {{", g.id, caps.join(", "), rty(&g.elem));
        let mut e = FnEmit { f, ctx: Ctx::Gen, out: String::new(), ind: 2 };
        e.decls(&[]);
        for v in &g.captures {
            e.line(&format!("v{v} = c{v};"));
        }
        e.block(&f.body);
        let _ = writeln!(out, "    Gen::new(gen move {{\n{}    }})\n}}\n", e.out);
    }
    for w in &p.workers {
        let f = &w.func;
        let param = f.params[0];
        let _ = writeln!(out, "fn worker{}(v{param}: {}) -> {} {{", w.id, rty(&w.input), rty(&f.ret));
        let mut e = FnEmit { f, ctx: Ctx::Worker, out: String::new(), ind: 1 };
        e.decls(&f.params);
        e.block(&f.body);
        e.line("unreachable!()");
        out.push_str(&e.out);
        out.push_str("}\n\n");
    }
    for f in &p.funcs {
        let params: Vec<String> = f.params.iter().map(|v| format!("v{v}: {}", rty(&f.vars[*v].ty))).collect();
        let ctx = if f.is_main { Ctx::Main } else { Ctx::Plain };
        let ret = if f.ret != LTy::Unit { format!(" -> {}", rty(&f.ret)) } else { String::new() };
        let _ = writeln!(out, "fn {}({}){} {{", f.name, params.join(", "), ret);
        let mut e = FnEmit { f, ctx, out: String::new(), ind: 1 };
        // Parameters are rebindable locals.
        for v in &f.params {
            e.line(&format!("let mut v{v} = v{v};"));
        }
        e.decls(&f.params);
        e.block(&f.body);
        match ctx {
            Ctx::Plain if f.ret != LTy::Unit => e.line("unreachable!()"),
            _ => {}
        }
        out.push_str(&e.out);
        out.push_str("}\n\n");
    }
    if let Some(m) = p.funcs.iter().find(|f| f.is_main) {
        let _ = writeln!(out, "fn main() {{\n    {}();\n}}", m.name);
    }
    out
}

/// The platform constants `alx_sys_const` knows, as the C runtime has them
/// (so the oracle sees this machine's values without a second table).
#[cfg(not(target_arch = "wasm32"))]
fn sys_consts() -> Vec<(String, i64)> {
    unsafe extern "C" {
        fn alx_sys_const_count() -> i64;
        fn alx_sys_const_name(i: i64) -> *const std::ffi::c_char;
        fn alx_sys_const(name: *const std::ffi::c_char) -> i64;
    }
    unsafe {
        (0..alx_sys_const_count())
            .map(|i| {
                let n = alx_sys_const_name(i);
                (std::ffi::CStr::from_ptr(n).to_string_lossy().into_owned(), alx_sys_const(n))
            })
            .collect()
    }
}
#[cfg(target_arch = "wasm32")]
fn sys_consts() -> Vec<(String, i64)> {
    vec![]
}

/// Rust-side types of an `extern def` in the C ABI.
fn ffi_rty(t: FfiTy) -> &'static str {
    match t {
        FfiTy::Int(k) => match k {
            IntKind::I8 => "i8",
            IntKind::I16 => "i16",
            IntKind::I32 => "i32",
            IntKind::I64 => "i64",
            IntKind::U8 => "u8",
            IntKind::U16 => "u16",
            IntKind::U32 => "u32",
            IntKind::U64 => "u64",
        },
        FfiTy::F64 => "f64",
        FfiTy::Bool => "bool",
        FfiTy::Str => "*const std::ffi::c_char",
        FfiTy::Bytes => "*mut u8",
        FfiTy::Ptr => "*mut std::ffi::c_void",
        FfiTy::Unit => "()",
    }
}

/// One Rust function `ffi_N` per C function of the program (taking and
/// returning LIR register types), over an `extern "C"` declaration of the
/// symbol. The `alx_sys_*` shims of the C runtime are Rust functions in the
/// prelude instead (the oracle links no C).
fn ffi_fns(p: &LProgram) -> String {
    let mut o = String::new();
    let _ = writeln!(o, "fn sys_consts() -> &'static [(&'static str, i64)] {{\n    &[{}]\n}}\n", sys_consts().iter().map(|(n, v)| format!("({n:?}, {v}i64)")).collect::<Vec<_>>().join(", "));
    for (i, x) in p.externs.iter().enumerate() {
        let cparams: Vec<String> = x.params.iter().enumerate().map(|(k, t)| format!("a{k}: {}", ffi_rty(*t))).collect();
        let cret = if x.ret == FfiTy::Unit { String::new() } else { format!(" -> {}", ffi_rty(x.ret)) };
        // Every `alx_*` symbol is the C runtime's: the prelude has it as `shim_alx_*`.
        let shim_name = format!("shim_{}", x.sym);
        let shim = if x.sym.starts_with("alx_") { Some(shim_name.as_str()) } else { None };
        match shim {
            Some(f) => {
                let names: Vec<String> = (0..x.params.len()).map(|k| format!("a{k}")).collect();
                let _ = writeln!(o, "unsafe fn ffi_c_{i}({}){cret} {{ {f}({}) }}", cparams.join(", "), names.join(", "));
            }
            None => {
                let _ = writeln!(o, "unsafe extern \"C\" {{\n    #[link_name = {:?}]\n    fn ffi_c_{i}({}){cret};\n}}", x.sym, cparams.join(", "));
            }
        }
        let rparams: Vec<String> = x.params.iter().enumerate().map(|(k, t)| format!("a{k}: {}", rty(&t.lty()))).collect();
        let rret = if x.ret == FfiTy::Unit { String::new() } else { format!(" -> {}", rty(&x.ret.lty())) };
        let _ = writeln!(o, "fn ffi_{i}({}){rret} {{", rparams.join(", "));
        o.push_str("    { use std::io::Write; let _ = std::io::stdout().flush(); }\n");
        let mut args = vec![];
        let mut post = String::new();
        for (k, t) in x.params.iter().enumerate() {
            match t {
                FfiTy::Str => {
                    let _ = writeln!(o, "    let c{k} = std::ffi::CString::new(a{k}.0.iter().copied().take_while(|b| *b != 0).collect::<Vec<u8>>()).unwrap();");
                    args.push(format!("c{k}.as_ptr()"));
                }
                FfiTy::Bytes => {
                    let _ = writeln!(o, "    let mut b{k}: Vec<u8> = a{k}.to_vec().into_iter().map(|x| x as u8).collect();");
                    args.push(format!("b{k}.as_mut_ptr()"));
                    let _ = writeln!(post, "    a{k}.store_bytes(&b{k});");
                }
                FfiTy::Ptr => args.push(format!("a{k} as usize as *mut std::ffi::c_void")),
                FfiTy::Int(_) => args.push(format!("a{k} as {}", ffi_rty(*t))),
                _ => args.push(format!("a{k}")),
            }
        }
        let call = format!("unsafe {{ ffi_c_{i}({}) }}", args.join(", "));
        let _ = writeln!(o, "    clear_errno();\n    let r = {call};\n    save_errno();\n{post}    {}\n}}\n", match x.ret {
            FfiTy::Int(_) => "r as i64",
            FfiTy::Ptr => "r as usize as i64",
            _ => "r",
        });
    }
    o
}

struct FnEmit<'f> {
    f: &'f LFunc,
    ctx: Ctx,
    out: String,
    ind: usize,
}

impl FnEmit<'_> {
    fn line(&mut self, s: &str) {
        for _ in 0..self.ind {
            self.out.push_str("    ");
        }
        self.out.push_str(s);
        self.out.push('\n');
    }

    fn decls(&mut self, skip: &[V]) {
        for (i, v) in self.f.vars.iter().enumerate() {
            if !skip.contains(&i) {
                self.line(&format!("let mut v{i}: {} = Default::default();", rty(&v.ty)));
            }
        }
    }

    fn block(&mut self, ss: &[LS]) {
        for s in ss {
            self.stmt(s);
        }
    }

    fn stmt(&mut self, s: &LS) {
        match s {
            LS::SetGlobal(k, v) => {
                let v = self.e(v);
                self.line(&format!("let _ = G{k}.set({v});"));
            }
            LS::RegionFree(_) => {}
            // Rust owns its memory: regions are meaningless here.
            LS::RegionEnter { .. } | LS::RegionExit { .. } | LS::RegionUse { .. } | LS::RegionRestore(_) => {}
            LS::Spawn { dst, worker, env } => {
                let x = self.e(env);
                self.line(&format!("v{dst} = task_spawn(worker{worker}, {x});"));
            }
            LS::Wait { task, ok, val, msg } => {
                let t = self.e(task);
                self.line(&format!("match ({t}).wait() {{ Ok(x_) => {{ v{ok} = true; v{val} = x_; }} Err(m_) => {{ v{ok} = false; v{msg} = m_; }} }}"));
            }
            LS::ChanSend { ch, val, loc: l } => {
                let (c, x) = (self.e(ch), self.e(val));
                self.line(&format!("{{ let c_ = {c}; let x_ = {x}; c_.send(x_, {}); }}", loc(l)));
            }
            LS::ChanRecv { ch, ok, val } => {
                let c = self.e(ch);
                self.line(&format!("match ({c}).recv() {{ Some(x_) => {{ v{ok} = true; v{val} = x_; }} None => {{ v{ok} = false; }} }}"));
            }
            LS::ChanClose { ch, loc: l } => {
                let c = self.e(ch);
                self.line(&format!("({c}).close({});", loc(l)));
            }
            LS::Lock(l) => {
                let l = self.e(l);
                self.line(&format!("({l}).lock();"));
            }
            LS::Unlock(l) => {
                let l = self.e(l);
                self.line(&format!("({l}).unlock();"));
            }
            LS::AtomicStore(a, v) => {
                let (a, v) = (self.e(a), self.e(v));
                self.line(&format!("({a}).store({v});"));
            }
            LS::Select { cases, default, dst } => {
                // Case expressions are evaluated once, in order, into `s{i}_`.
                let mut code = String::from("{ ");
                for (i, c) in cases.iter().enumerate() {
                    match c {
                        SelCase::Send { ch, val } => {
                            let (c, x) = (self.e(ch), self.e(val));
                            code.push_str(&format!("let c{i}_ = {c}; let x{i}_ = {x}; let mut s{i}_ = SelSend::new(c{i}_, x{i}_); "));
                        }
                        SelCase::Recv { ch, .. } => {
                            code.push_str(&format!("let mut s{i}_ = SelRecv::new({}); ", self.e(ch)));
                        }
                    }
                }
                let refs: Vec<String> = (0..cases.len()).map(|i| format!("&mut s{i}_ as &mut dyn SelCase")).collect();
                code.push_str(&format!("v{dst} = select(&mut [{}], {default}); ", refs.join(", ")));
                for (i, c) in cases.iter().enumerate() {
                    if let SelCase::Recv { ok, val, .. } = c {
                        code.push_str(&format!("if v{dst} == {i} {{ match s{i}_.result() {{ Some(x_) => {{ v{ok} = true; v{val} = x_; }} None => {{ v{ok} = false; }} }} }} "));
                    }
                }
                code.push('}');
                self.line(&code);
            }
            LS::Set(v, e) => {
                let x = self.e(e);
                self.line(&format!("v{v} = {x};"));
            }
            LS::SetIndex { arr, idx, val, check } => {
                let (i, x) = (self.e(idx), self.e(val));
                let at = match check {
                    Some(l) => format!("idx({i}, v{arr}.len(), {})", loc(l)),
                    None => format!("({i}) as usize"),
                };
                self.line(&format!("{{ let x_ = {x}; let i_ = {at}; v{arr}.with(i_, |e_| *e_ = x_); }}"));
            }
            LS::SetPlace { var, steps, val } => {
                // Indices first (each bounds-checked against the array it
                // indexes), then one write: keeps the borrow checker happy.
                // Slices write through `with` (shared storage), nesting one
                // closure per index step.
                // Index values are computed before any lock is taken.
                let mut code = format!("{{ let x_ = {};", self.e(val));
                for (k, st) in steps.iter().enumerate() {
                    if let Step::Index(i, _) = st {
                        code.push_str(&format!(" let j{k}_ = {};", self.e(i)));
                    }
                }
                let mut lv = format!("v{var}");
                let mut opens = 0;
                for (k, st) in steps.iter().enumerate() {
                    lv = match st {
                        Step::Index(_, check) => {
                            let at = match check {
                                Some(l) => format!("idx(j{k}_, {lv}.len(), {})", loc(l)),
                                None => format!("j{k}_ as usize"),
                            };
                            code.push_str(&format!(" let i{k}_ = {at}; {lv}.with(i{k}_, |e{k}_| {{"));
                            opens += 1;
                            format!("(*e{k}_)")
                        }
                        Step::Field(f) => format!("{lv}.{f}"),
                    };
                }
                self.line(&format!("{code} {lv} = x_; {} }}", "});".repeat(opens)));
            }
            LS::Push(v, e) => {
                let x = self.e(e);
                self.line(&format!("{{ let x_ = {x}; v{v}.push(x_); }}"));
            }
            LS::Eval(e) => {
                let x = self.e(e);
                self.line(&format!("let _ = {x};"));
            }
            LS::If(c, a, b) => {
                let c = self.e(c);
                self.line(&format!("if {c} {{"));
                self.ind += 1;
                self.block(a);
                self.ind -= 1;
                if b.is_empty() {
                    self.line("}");
                } else {
                    self.line("} else {");
                    self.ind += 1;
                    self.block(b);
                    self.ind -= 1;
                    self.line("}");
                }
            }
            LS::Loop(l, body) => {
                self.line(&format!("'l{l}: loop {{"));
                self.ind += 1;
                self.block(body);
                self.ind -= 1;
                self.line("}");
            }
            LS::Break(l) => self.line(&format!("break 'l{l};")),
            LS::Continue(l) => self.line(&format!("continue 'l{l};")),
            LS::Return(v) => {
                let x = v.as_ref().map(|v| self.e(v));
                match (self.ctx, x) {
                    (Ctx::Worker, Some(x)) => self.line(&format!("return {x};")),
                    (Ctx::Plain, Some(x)) => self.line(&format!("return {x};")),
                    _ => self.line("return;"),
                }
            }
            LS::NextOrBreak { source, dst, label } => {
                let g = self.e(source);
                self.line(&format!("match ({g}).next() {{ Some(x_) => v{dst} = x_, None => break 'l{label} }}"));
            }
            LS::Yield(e) => {
                let x = self.e(e);
                self.line(&format!("yield {x};"));
            }
            LS::Pmap { dst, arr, worker, err } => {
                let a = self.e(arr);
                match err {
                    None => self.line(&format!("v{dst} = pmap(&{a}, worker{worker});")),
                    Some(e) => self.line(&format!(
                        "{{ let r_ = pmap(&{a}, worker{worker}).to_vec(); let mut o_ = Vec::with_capacity(r_.len()); v{e} = Default::default(); v{e}.0 = true; \
                         for x_ in r_ {{ if !x_.0 {{ v{e} = x_; break; }} o_.push(x_.1); }} v{dst} = Sl::from(o_); }}"
                    )),
                }
            }
            LS::Print(e) => {
                let x = self.e(e);
                self.line(&format!("print_str({x});"));
            }
            LS::Puts(e, t) => {
                let x = self.e(e);
                match t {
                    LTy::I64 => self.line(&format!("puts_i64({x});")),
                    LTy::IntK(IntKind::U64) => self.line(&format!("println!(\"{{}}\", ({x}) as u64);")),
                    LTy::IntK(_) => self.line(&format!("puts_i64({x});")),
                    LTy::F64 => self.line(&format!("puts_str(f_to_s({x}));")),
                    LTy::Str => self.line(&format!("puts_str({x});")),
                    LTy::Bool => self.line(&format!("puts_bool({x});")),
                    LTy::PInt => self.line(&format!("puts_pint({x});")),
                    _ => self.line(&format!("let _ = {x}; println!();")),
                }
            }
            LS::Die(e) => {
                let x = self.e(e);
                self.line(&format!("die_str({x});"));
            }
            LS::Panic(m, l) => self.line(&format!("panic({:?}, {});", m, loc(l))),
            LS::Exit(e) => {
                let x = self.e(e);
                self.line(&format!("{{ use std::io::Write; let _ = std::io::stdout().flush(); std::process::exit(({x}) as i32); }}"));
            }
            LS::PanicStr(e) => {
                let x = self.e(e);
                self.line(&format!("panic_str({x});"));
            }
            LS::SortInPlace(v, _) => self.line(&format!("v{v}.sort();")),
        }
    }

    fn var(&self, v: V) -> String {
        if is_copy(&self.f.vars[v].ty) { format!("v{v}") } else { format!("v{v}.clone()") }
    }

    /// An expression as a place to read from without moving (for indexing).
    fn place(&self, e: &LE) -> String {
        match e {
            LE::Var(v) => format!("v{v}"),
            _ => format!("({})", self.e(e)),
        }
    }

    fn e(&self, e: &LE) -> String {
        match e {
            LE::Global(k) => format!("G{k}.get().unwrap().clone()"),
            LE::RegionNew(_) => "()".into(),
            LE::RegionBytes(_) => "(0i64)".into(),
            LE::RegionOf(_) => "()".into(),
            LE::RegionProgram => "()".into(),
            LE::ChanNew(t, cap) => format!("Chan::<{}>::new({})", rty(t), self.e(cap)),
            LE::ChanLen(c) => format!("({}).len()", self.e(c)),
            LE::LockNew => "AlxLock::default()".into(),
            LE::AtomicNew(v) => format!("AlxAtomic::new({})", self.e(v)),
            LE::AtomicLoad(a) => format!("({}).load()", self.e(a)),
            LE::AtomicRmw(AtomicOp::Add, a, v) => format!("({}).add({})", self.e(a), self.e(v)),
            LE::AtomicRmw(AtomicOp::Swap, a, v) => format!("({}).swap({})", self.e(a), self.e(v)),
            LE::AtomicCas(a, o, n) => format!("({}).cas({}, {})", self.e(a), self.e(o), self.e(n)),
            LE::Var(v) => self.var(*v),
            LE::I(i) => {
                if *i == i64::MIN {
                    "i64::MIN".into()
                } else {
                    format!("({i}i64)")
                }
            }
            LE::F(v) => {
                if v.is_nan() {
                    "f64::NAN".into()
                } else if v.is_infinite() {
                    if *v > 0.0 { "f64::INFINITY".into() } else { "f64::NEG_INFINITY".into() }
                } else {
                    format!("({v:?}f64)")
                }
            }
            LE::FArith(op, a, b) => {
                let sym = match op {
                    Op::Add => "+",
                    Op::Sub => "-",
                    Op::Mul => "*",
                    _ => "/",
                };
                format!("(({}) {sym} ({}))", self.e(a), self.e(b))
            }
            LE::FNeg(x) => format!("(-({}))", self.e(x)),
            LE::Prim(p, args) => {
                let a: Vec<String> = args.iter().map(|x| self.e(x)).collect();
                let u = |x: &str| format!("(({x}) as u64)");
                match p {
                    Prim::And => format!("(({}) & ({}))", a[0], a[1]),
                    Prim::Or => format!("(({}) | ({}))", a[0], a[1]),
                    Prim::Xor => format!("(({}) ^ ({}))", a[0], a[1]),
                    Prim::AndNot => format!("(({}) & !({}))", a[0], a[1]),
                    Prim::Not => format!("(!({}))", a[0]),
                    Prim::Shl => format!("(({}).wrapping_shl(({}) as u32))", a[0], a[1]),
                    Prim::ShrS => format!("(({}) >> ({}))", a[0], a[1]),
                    Prim::ShrU => format!("(({} >> ({})) as i64)", u(&a[0]), a[1]),
                    Prim::MulOvf => format!("(({}).checked_mul({}).is_none())", a[0], a[1]),
                    Prim::ULt => format!("({} < {})", u(&a[0]), u(&a[1])),
                    Prim::ULe => format!("({} <= {})", u(&a[0]), u(&a[1])),
                    Prim::UDiv => format!("(({} / {}) as i64)", u(&a[0]), u(&a[1])),
                    Prim::URem => format!("(({} % {}) as i64)", u(&a[0]), u(&a[1])),
                    Prim::UMulHi => format!("((({} as u128 * {} as u128) >> 64) as i64)", u(&a[0]), u(&a[1])),
                    Prim::Wrap(k) => {
                        let t = match k {
                            IntKind::I8 => "i8",
                            IntKind::I16 => "i16",
                            IntKind::I32 => "i32",
                            IntKind::U8 => "u8",
                            IntKind::U16 => "u16",
                            IntKind::U32 => "u32",
                            _ => "i64",
                        };
                        format!("((({}) as {t}) as i64)", a[0])
                    }
                    Prim::UToF => format!("({} as f64)", u(&a[0])),
                }
            }
            LE::B(b) => b.to_string(),
            LE::S(s) => format!("Str::lit({})", lit(s)),
            LE::Loc(s) => loc(s),
            LE::Unit => "()".into(),
            LE::Tup(_, vs) if vs.is_empty() => "()".into(),
            LE::Tup(t, vs) if vs.len() > 12 => format!("{}({})", rty(t), vs.iter().map(|x| self.e(x)).collect::<Vec<_>>().join(", ")),
            LE::Tup(_, vs) => format!("({},)", vs.iter().map(|x| self.e(x)).collect::<Vec<_>>().join(", ")),
            LE::Field(x, i) => format!("{}.{i}.clone()", self.place(x)),
            LE::Arith(op, a, b, ovf) => {
                let (a, b) = (self.e(a), self.e(b));
                let name = match op {
                    Op::Add => "add",
                    Op::Sub => "sub",
                    Op::Mul => "mul",
                    Op::Div => "div",
                    Op::Rem => "rem",
                    _ => "pow",
                };
                match ovf {
                    Ovf::Panic(l) => format!("{name}({a}, {b}, {})", loc(l)),
                    Ovf::Wrap | Ovf::Unchecked => match op {
                        Op::Add => format!("({a}).wrapping_add({b})"),
                        Op::Sub => format!("({a}).wrapping_sub({b})"),
                        Op::Mul => format!("({a}).wrapping_mul({b})"),
                        _ => format!("{name}({a}, {b}, \"proven\")"),
                    },
                }
            }
            LE::PArith(op, a, b) => {
                let (a, b) = (self.e(a), self.e(b));
                match op {
                    Op::Add => format!("({a}).add(&{b})"),
                    Op::Sub => format!("({a}).sub(&{b})"),
                    Op::Mul => format!("({a}).mul(&{b})"),
                    Op::Div => format!("({a}).div(&{b}, \"div\")"),
                    Op::Rem => format!("({a}).rem(&{b}, \"rem\")"),
                    Op::Pow => format!("({a}).pow(&{b}, \"pow\")"),
                    Op::Eq => format!("(({a}).cmp(&{b}) == std::cmp::Ordering::Equal)"),
                    Op::Ne => format!("(({a}).cmp(&{b}) != std::cmp::Ordering::Equal)"),
                    Op::Lt => format!("(({a}).cmp(&{b}) == std::cmp::Ordering::Less)"),
                    Op::Le => format!("(({a}).cmp(&{b}) != std::cmp::Ordering::Greater)"),
                    Op::Gt => format!("(({a}).cmp(&{b}) == std::cmp::Ordering::Greater)"),
                    Op::Ge => format!("(({a}).cmp(&{b}) != std::cmp::Ordering::Less)"),
                    _ => unreachable!(),
                }
            }
            LE::Cmp(op, a, b, t) => {
                let (a, b) = (self.e(a), self.e(b));
                let sym = match op {
                    Op::Eq => "==",
                    Op::Ne => "!=",
                    Op::Lt => "<",
                    Op::Le => "<=",
                    Op::Gt => ">",
                    Op::Ge => ">=",
                    Op::And => "&&",
                    Op::Or => "||",
                    _ => unreachable!(),
                };
                if *t == LTy::PInt {
                    return format!("(({a}).cmp(&{b}) {sym} std::cmp::Ordering::Equal)");
                }
                format!("(({a}) {sym} ({b}))")
            }
            LE::Neg(x, ovf) => match ovf {
                Ovf::Panic(l) => format!("neg({}, {})", self.e(x), loc(l)),
                _ => format!("({}).wrapping_neg()", self.e(x)),
            },
            LE::Not(x) => format!("(!{})", self.e(x)),
            LE::Cond(c, a, b) => format!("(if {} {{ {} }} else {{ {} }})", self.e(c), self.e(a), self.e(b)),
            LE::Call(f, args) => format!("{f}({})", args.iter().map(|x| self.e(x)).collect::<Vec<_>>().join(", ")),
            LE::Ffi(i, args) => format!("ffi_{i}({})", args.iter().map(|x| self.e(x)).collect::<Vec<_>>().join(", ")),
            LE::Rt(rt, args) => {
                let a: Vec<String> = args.iter().map(|x| self.e(x)).collect();
                let p0 = args.first().map(|x| self.place(x)).unwrap_or_default();
                let call = |f: &str| format!("{f}({})", a.join(", "));
                match rt {
                    Rt::IntToS => call("int_to_s"),
                    Rt::PIntToS => format!("({}).to_s()", a[0]),
                    Rt::StrRev => call("str_rev"),
                    Rt::StrDelete => call("str_delete"),
                    Rt::StrSplit => call("str_split"),
                    Rt::StrJoin => call("str_join"),
                    Rt::StrToI => call("str_to_i"),
                    Rt::StrIndex => call("str_index"),
                    Rt::StrChar => format!("str_charlen(&{p0}, {})", a[1]),
                    Rt::StrByte => {
                        if a[2] == "(0i64)" {
                            format!("str_byte(&{p0}, {})", a[1])
                        } else {
                            format!("str_sub(&{p0}, {}, {})", a[1], a[2])
                        }
                    }
                    Rt::StrLen => format!("{p0}.len()"),
                    Rt::NDigits => format!("{}.len()", call("int_to_s")),
                    Rt::PNDigits => format!("({}).to_s().len()", a[0]),
                    Rt::Isqrt => call("isqrt"),
                    Rt::Digits => call("digits"),
                    Rt::PDigits => format!("Sl::from(({}).digits({}))", a[0], a[1]),
                    Rt::SatAdd => call("sat_add"),
                    Rt::ArrCopy => format!("Sl::from(({}).to_vec())", a[0]),
                    Rt::Even => call("even"),
                    Rt::PEven => format!("({}).even()", a[0]),
                    Rt::PToI64 => format!("({}).to_i64({})", a[0], a[1]),
                    Rt::PFromStr => format!("PInt::from_str_ruby(&{})", a[0]),
                    Rt::IntToF => format!("(({}) as f64)", a[0]),
                    Rt::FToI => call("f_to_i"),
                    Rt::FSqrt => format!("({}).sqrt()", a[0]),
                    Rt::FAbs => format!("({}).abs()", a[0]),
                    Rt::Math(f) => call(&format!("m_{}", f.c_name())),
                    Rt::FBits => format!("(({}).to_bits() as i64)", a[0]),
                    Rt::FFromBits => format!("f64::from_bits(({}) as u64)", a[0]),
                    Rt::FToS => call("f_to_s"),
                    Rt::FFmt => call("f_fmt"),
                    Rt::FFmtE => call("f_fmt_e"),
                    Rt::StrPad => call("str_pad"),
                    Rt::StrQuote => call("str_quote"),
                    Rt::StrCat => format!("str_cat(vec![{}])", a.join(", ")),
                    Rt::U64ToS => format!("Str::lit((({}) as u64).to_string().as_bytes())", a[0]),
                    Rt::IntFmt => call("int_fmt"),
                    Rt::FToU64 => call("f_to_u64"),
                    Rt::RuneToS => call("rune_to_s"),
                    Rt::FileStatus => call("file_status"),
                    Rt::FileRead => call("file_read_or_empty"),
                    Rt::NowNs => call("now_ns"),
                    Rt::RegionCur | Rt::RegionMark | Rt::RegionMarkLarges => "()".to_string(),
                    Rt::RegionReset => "()".to_string(),
                    Rt::Errno => call("errno"),
                    Rt::Strerror => call("strerror_str"),
                    Rt::StrFromCstr => call("str_from_cstr"),
                    Rt::StrFromPtr => call("str_from_ptr"),
                    Rt::CapBegin => call("cap_begin"),
                    Rt::CapEnd => call("cap_end"),
                    Rt::StrFromBytes => format!("Str(({}).to_vec().into_iter().map(|b| b as u8).collect::<Vec<u8>>().into())", a[0]),
                }
            }
            LE::Index { arr, idx, check } => {
                let p = self.place(arr);
                let i = self.e(idx);
                match check {
                    Some(l) => format!("{p}.get(idx({i}, {p}.len(), {}))", loc(l)),
                    None => format!("{p}.get(({i}) as usize)"),
                }
            }
            LE::Len(x) => format!("({}.len() as i64)", self.place(x)),
            LE::ArrLit(_, vs) => format!("Sl::from(vec![{}])", vs.iter().map(|x| self.e(x)).collect::<Vec<_>>().join(", ")),
            LE::ArrNew(_, n, fill, l) => format!("arr_new({}, {}, {})", self.e(n), self.e(fill), loc(l)),
            LE::ArrWithCap(_, n) => format!("Sl::with_cap(cap({}))", self.e(n)),
            LE::Slice(_, a, start, len) => {
                let p = self.place(a);
                let (s, n) = (self.e(start), self.e(len));
                format!("{p}.slice(({s}) as usize, ({n}) as usize)")
            }
            LE::Range(lo, hi, ex) => format!("AlxRange {{ lo: {}, hi: {}, excl: {ex} }}", self.e(lo), self.e(hi)),
            LE::RangeField(r, k) => format!("{}.{}", self.place(r), ["lo", "hi", "excl"][*k as usize]),
            LE::GenNew(id, vals) => format!("gen_new_{id}({})", vals.iter().map(|x| self.e(x)).collect::<Vec<_>>().join(", ")),
            LE::ToP(x) => format!("PInt::from_i64({})", self.e(x)),
        }
    }
}
