//! LIR → Rust: the oracle backend. The output is checked (and can be run)
//! with rustc; if rustc rejects a program our checker accepted, our checker
//! has a bug (DESIGN.md, Architecture).

use crate::lir::*;
use std::fmt::Write;

const PRELUDE: &str = include_str!("../runtime/prelude.rs");

fn rty(t: &LTy) -> String {
    match t {
        // Every integer kind is an i64 here (bit pattern for U64): the
        // oracle checks meaning, not memory layout.
        LTy::I64 | LTy::IntK(_) => "i64".into(),
        LTy::F64 => "f64".into(),
        LTy::PInt => "PInt".into(),
        LTy::Bool => "bool".into(),
        LTy::Str => "Str".into(),
        LTy::Unit => "()".into(),
        LTy::Arr(t) => format!("Vec<{}>", rty(t)),
        LTy::Tup(ts) => format!("({},)", ts.iter().map(rty).collect::<Vec<_>>().join(", ")),
        LTy::Range => "AlxRange".into(),
        LTy::Gen(t) => format!("Gen<{}>", rty(t)),
    }
}

fn is_copy(t: &LTy) -> bool {
    matches!(t, LTy::I64 | LTy::IntK(_) | LTy::F64 | LTy::Bool | LTy::Unit | LTy::Range)
}

fn lit(s: &str) -> String {
    let mut o = String::from("b\"");
    for b in s.bytes() {
        match b {
            b'"' => o.push_str("\\\""),
            b'\\' => o.push_str("\\\\"),
            b'\n' => o.push_str("\\n"),
            0x20..=0x7e => o.push(b as char),
            _ => {
                let _ = write!(o, "\\x{b:02x}");
            }
        }
    }
    o.push('"');
    o
}

fn loc(s: &str) -> String {
    format!("{s:?}")
}

#[derive(Clone, Copy, PartialEq)]
enum Ctx {
    Plain,
    Fallible,
    Main,
    Gen,
    Worker,
}

pub fn emit(p: &LProgram) -> String {
    let mut out = String::from(PRELUDE);
    out.push_str("\n// ---- generated by alx ----\n\n");
    for g in &p.gens {
        let f = &g.func;
        let caps: Vec<String> = g.captures.iter().map(|v| format!("c{v}: {}", rty(&f.vars[*v].ty))).collect();
        let _ = writeln!(out, "fn gen_new_{}({}) -> Gen<{}> {{", g.id, caps.join(", "), rty(&g.elem));
        let mut e = FnEmit { f, ctx: Ctx::Gen, out: String::new(), ind: 2 };
        e.decls(&[]);
        for v in &g.captures {
            e.line(&format!("v{v} = c{v};"));
        }
        e.block(&f.body);
        let _ = writeln!(out, "    Gen::new(gen move {{\n{}    }})\n}}\n", e.out);
    }
    for w in &p.workers {
        let f = &w.func;
        let param = f.params[0];
        let _ = writeln!(out, "fn worker{}(v{param}: {}) -> Result<{}, AlxErr> {{", w.id, rty(&w.input), rty(&f.ret));
        let mut e = FnEmit { f, ctx: Ctx::Worker, out: String::new(), ind: 1 };
        e.decls(&f.params);
        e.block(&f.body);
        e.line("unreachable!()");
        out.push_str(&e.out);
        out.push_str("}\n\n");
    }
    for f in &p.funcs {
        let params: Vec<String> = f.params.iter().map(|v| format!("v{v}: {}", rty(&f.vars[*v].ty))).collect();
        let ctx = if f.is_main {
            Ctx::Main
        } else if f.fallible {
            Ctx::Fallible
        } else {
            Ctx::Plain
        };
        let ret = match ctx {
            Ctx::Fallible => format!(" -> Result<{}, AlxErr>", rty(&f.ret)),
            _ if f.ret != LTy::Unit => format!(" -> {}", rty(&f.ret)),
            _ => String::new(),
        };
        let _ = writeln!(out, "fn {}({}){} {{", f.name, params.join(", "), ret);
        let mut e = FnEmit { f, ctx, out: String::new(), ind: 1 };
        // Parameters are rebindable locals.
        for v in &f.params {
            e.line(&format!("let mut v{v} = v{v};"));
        }
        e.decls(&f.params);
        e.block(&f.body);
        match ctx {
            Ctx::Fallible if f.ret == LTy::Unit => e.line("Ok(())"),
            Ctx::Fallible | Ctx::Plain if f.ret != LTy::Unit => e.line("unreachable!()"),
            _ => {}
        }
        out.push_str(&e.out);
        out.push_str("}\n\n");
    }
    if let Some(m) = p.funcs.iter().find(|f| f.is_main) {
        let _ = writeln!(out, "fn main() {{\n    {}();\n}}", m.name);
    }
    out
}

struct FnEmit<'f> {
    f: &'f LFunc,
    ctx: Ctx,
    out: String,
    ind: usize,
}

impl FnEmit<'_> {
    fn line(&mut self, s: &str) {
        for _ in 0..self.ind {
            self.out.push_str("    ");
        }
        self.out.push_str(s);
        self.out.push('\n');
    }

    fn decls(&mut self, skip: &[V]) {
        for (i, v) in self.f.vars.iter().enumerate() {
            if !skip.contains(&i) {
                self.line(&format!("let mut v{i}: {} = Default::default();", rty(&v.ty)));
            }
        }
    }

    fn block(&mut self, ss: &[LS]) {
        for s in ss {
            self.stmt(s);
        }
    }

    fn err_path(&mut self, path: &ErrPath, e: &str) {
        self.block(path.cleanup());
        match (path, self.ctx) {
            (ErrPath::Return(_), Ctx::Fallible | Ctx::Worker) => self.line(&format!("return Err({e});")),
            _ => self.line(&format!("die({e});")),
        }
    }

    fn stmt(&mut self, s: &LS) {
        match s {
            LS::Set(v, e) => {
                let x = self.e(e);
                self.line(&format!("v{v} = {x};"));
            }
            LS::SetIndex { arr, idx, val, check } => {
                let (i, x) = (self.e(idx), self.e(val));
                let at = match check {
                    Some(l) => format!("idx({i}, v{arr}.len(), {})", loc(l)),
                    None => format!("({i}) as usize"),
                };
                self.line(&format!("{{ let i_ = {at}; v{arr}[i_] = {x}; }}"));
            }
            LS::SetPlace { var, steps, val } => {
                // Indices first (each bounds-checked against the array it
                // indexes), then one write: keeps the borrow checker happy.
                let mut code = format!("{{ let x_ = {};", self.e(val));
                let mut lv = format!("v{var}");
                for (k, st) in steps.iter().enumerate() {
                    lv = match st {
                        Step::Index(i, check) => {
                            let at = match check {
                                Some(l) => format!("idx({}, {lv}.len(), {})", self.e(i), loc(l)),
                                None => format!("({}) as usize", self.e(i)),
                            };
                            code.push_str(&format!(" let i{k}_ = {at};"));
                            format!("{lv}[i{k}_]")
                        }
                        Step::Field(f) => format!("{lv}.{f}"),
                    };
                }
                self.line(&format!("{code} {lv} = x_; }}"));
            }
            LS::FailIf { cond, loc: l, path } => {
                let c = self.e(cond);
                self.line(&format!("if {c} {{"));
                self.ind += 1;
                self.err_path(path, &format!("err_overflow({})", loc(l)));
                self.ind -= 1;
                self.line("}");
            }
            LS::Push(v, e) => {
                let x = self.e(e);
                self.line(&format!("{{ let x_ = {x}; v{v}.push(x_); }}"));
            }
            LS::Eval(e) => {
                let x = self.e(e);
                self.line(&format!("let _ = {x};"));
            }
            LS::If(c, a, b) => {
                let c = self.e(c);
                self.line(&format!("if {c} {{"));
                self.ind += 1;
                self.block(a);
                self.ind -= 1;
                if b.is_empty() {
                    self.line("}");
                } else {
                    self.line("} else {");
                    self.ind += 1;
                    self.block(b);
                    self.ind -= 1;
                    self.line("}");
                }
            }
            LS::Loop(l, body) => {
                self.line(&format!("'l{l}: loop {{"));
                self.ind += 1;
                self.block(body);
                self.ind -= 1;
                self.line("}");
            }
            LS::Break(l) => self.line(&format!("break 'l{l};")),
            LS::Continue(l) => self.line(&format!("continue 'l{l};")),
            LS::Return(v) => {
                let x = v.as_ref().map(|v| self.e(v));
                match (self.ctx, x) {
                    (Ctx::Fallible | Ctx::Worker, Some(x)) => self.line(&format!("return Ok({x});")),
                    (Ctx::Fallible | Ctx::Worker, None) => self.line("return Ok(Default::default());"),
                    (Ctx::Plain, Some(x)) => self.line(&format!("return {x};")),
                    _ => self.line("return;"),
                }
            }
            LS::TryArith { dst, op, a, b, loc: l, path } => {
                let f = match op {
                    Op::Add => "try_add",
                    Op::Sub => "try_sub",
                    Op::Mul => "try_mul",
                    Op::Div => "try_div",
                    Op::Rem => "try_rem",
                    _ => "try_pow",
                };
                let (a, b) = (self.e(a), self.e(b));
                self.line(&format!("match {f}({a}, {b}) {{ Some(r_) => v{dst} = r_, None => {{"));
                self.ind += 1;
                self.err_path(path, &format!("err_overflow({})", loc(l)));
                self.ind -= 1;
                self.line("} }");
            }
            LS::TryCall { dst, f, args, path } => {
                let a: Vec<String> = args.iter().map(|x| self.e(x)).collect();
                let set = match dst {
                    Some(d) => format!("v{d} = r_"),
                    None => "{}".into(),
                };
                self.line(&format!("match {f}({}) {{ Ok(r_) => {set}, Err(e_) => {{", a.join(", ")));
                self.ind += 1;
                self.err_path(path, "e_");
                self.ind -= 1;
                self.line("} }");
            }
            LS::TryRead { dst, path_arg, loc: l, path } => {
                let p = self.e(path_arg);
                self.line(&format!("match file_read({p}, {}) {{ Ok(r_) => v{dst} = r_, Err(e_) => {{", loc(l)));
                self.ind += 1;
                self.err_path(path, "e_");
                self.ind -= 1;
                self.line("} }");
            }
            LS::NextOrBreak { source, dst, label } => {
                let g = self.e(source);
                self.line(&format!("match ({g}).next() {{ Some(x_) => v{dst} = x_, None => break 'l{label} }}"));
            }
            LS::Yield(e) => {
                let x = self.e(e);
                self.line(&format!("yield {x};"));
            }
            LS::Pmap { dst, arr, worker, path } => {
                let a = self.e(arr);
                self.line(&format!("match pmap(&{a}, worker{worker}) {{ Ok(r_) => v{dst} = r_, Err(e_) => {{"));
                self.ind += 1;
                self.err_path(path, "e_");
                self.ind -= 1;
                self.line("} }");
            }
            LS::Puts(e, t) => {
                let x = self.e(e);
                match t {
                    LTy::I64 => self.line(&format!("puts_i64({x});")),
                    LTy::IntK(IntKind::U64) => self.line(&format!("println!(\"{{}}\", ({x}) as u64);")),
                    LTy::IntK(_) => self.line(&format!("puts_i64({x});")),
                    LTy::F64 => self.line(&format!("puts_str(f_to_s({x}));")),
                    LTy::Str => self.line(&format!("puts_str({x});")),
                    LTy::Bool => self.line(&format!("puts_bool({x});")),
                    LTy::PInt => self.line(&format!("puts_pint({x});")),
                    _ => self.line(&format!("let _ = {x}; println!();")),
                }
            }
            LS::Panic(m, l) => self.line(&format!("panic({:?}, {});", m, loc(l))),
            LS::SortInPlace(v, _) => self.line(&format!("v{v}.sort();")),
        }
    }

    fn var(&self, v: V) -> String {
        if is_copy(&self.f.vars[v].ty) { format!("v{v}") } else { format!("v{v}.clone()") }
    }

    /// An expression as a place to read from without moving (for indexing).
    fn place(&self, e: &LE) -> String {
        match e {
            LE::Var(v) => format!("v{v}"),
            _ => format!("({})", self.e(e)),
        }
    }

    fn e(&self, e: &LE) -> String {
        match e {
            LE::Var(v) => self.var(*v),
            LE::I(i) => {
                if *i == i64::MIN {
                    "i64::MIN".into()
                } else {
                    format!("({i}i64)")
                }
            }
            LE::F(v) => {
                if v.is_nan() {
                    "f64::NAN".into()
                } else if v.is_infinite() {
                    if *v > 0.0 { "f64::INFINITY".into() } else { "f64::NEG_INFINITY".into() }
                } else {
                    format!("({v:?}f64)")
                }
            }
            LE::FArith(op, a, b) => {
                let sym = match op {
                    Op::Add => "+",
                    Op::Sub => "-",
                    Op::Mul => "*",
                    _ => "/",
                };
                format!("(({}) {sym} ({}))", self.e(a), self.e(b))
            }
            LE::FNeg(x) => format!("(-({}))", self.e(x)),
            LE::Prim(p, args) => {
                let a: Vec<String> = args.iter().map(|x| self.e(x)).collect();
                let u = |x: &str| format!("(({x}) as u64)");
                match p {
                    Prim::And => format!("(({}) & ({}))", a[0], a[1]),
                    Prim::Or => format!("(({}) | ({}))", a[0], a[1]),
                    Prim::Xor => format!("(({}) ^ ({}))", a[0], a[1]),
                    Prim::AndNot => format!("(({}) & !({}))", a[0], a[1]),
                    Prim::Not => format!("(!({}))", a[0]),
                    Prim::Shl => format!("(({}).wrapping_shl(({}) as u32))", a[0], a[1]),
                    Prim::ShrS => format!("(({}) >> ({}))", a[0], a[1]),
                    Prim::ShrU => format!("(({} >> ({})) as i64)", u(&a[0]), a[1]),
                    Prim::ULt => format!("({} < {})", u(&a[0]), u(&a[1])),
                    Prim::ULe => format!("({} <= {})", u(&a[0]), u(&a[1])),
                    Prim::UDiv => format!("(({} / {}) as i64)", u(&a[0]), u(&a[1])),
                    Prim::URem => format!("(({} % {}) as i64)", u(&a[0]), u(&a[1])),
                    Prim::UMulHi => format!("((({} as u128 * {} as u128) >> 64) as i64)", u(&a[0]), u(&a[1])),
                    Prim::Wrap(k) => {
                        let t = match k {
                            IntKind::I8 => "i8",
                            IntKind::I16 => "i16",
                            IntKind::I32 => "i32",
                            IntKind::U8 => "u8",
                            IntKind::U16 => "u16",
                            IntKind::U32 => "u32",
                            _ => "i64",
                        };
                        format!("((({}) as {t}) as i64)", a[0])
                    }
                    Prim::UToF => format!("({} as f64)", u(&a[0])),
                }
            }
            LE::B(b) => b.to_string(),
            LE::S(s) => format!("Str::lit({})", lit(s)),
            LE::Loc(s) => loc(s),
            LE::Unit => "()".into(),
            LE::Tup(_, vs) => format!("({},)", vs.iter().map(|x| self.e(x)).collect::<Vec<_>>().join(", ")),
            LE::Field(x, i) => format!("{}.{i}.clone()", self.place(x)),
            LE::Arith(op, a, b, ovf) => {
                let (a, b) = (self.e(a), self.e(b));
                let name = match op {
                    Op::Add => "add",
                    Op::Sub => "sub",
                    Op::Mul => "mul",
                    Op::Div => "div",
                    Op::Rem => "rem",
                    _ => "pow",
                };
                match ovf {
                    Ovf::Panic(l) => format!("{name}({a}, {b}, {})", loc(l)),
                    Ovf::Wrap | Ovf::Unchecked => match op {
                        Op::Add => format!("({a}).wrapping_add({b})"),
                        Op::Sub => format!("({a}).wrapping_sub({b})"),
                        Op::Mul => format!("({a}).wrapping_mul({b})"),
                        _ => format!("{name}({a}, {b}, \"proven\")"),
                    },
                }
            }
            LE::PArith(op, a, b) => {
                let (a, b) = (self.e(a), self.e(b));
                match op {
                    Op::Add => format!("({a}).add(&{b})"),
                    Op::Sub => format!("({a}).sub(&{b})"),
                    Op::Mul => format!("({a}).mul(&{b})"),
                    Op::Div => format!("({a}).div(&{b}, \"div\")"),
                    Op::Rem => format!("({a}).rem(&{b}, \"rem\")"),
                    Op::Pow => format!("({a}).pow(&{b}, \"pow\")"),
                    Op::Eq => format!("(({a}).cmp(&{b}) == std::cmp::Ordering::Equal)"),
                    Op::Ne => format!("(({a}).cmp(&{b}) != std::cmp::Ordering::Equal)"),
                    Op::Lt => format!("(({a}).cmp(&{b}) == std::cmp::Ordering::Less)"),
                    Op::Le => format!("(({a}).cmp(&{b}) != std::cmp::Ordering::Greater)"),
                    Op::Gt => format!("(({a}).cmp(&{b}) == std::cmp::Ordering::Greater)"),
                    Op::Ge => format!("(({a}).cmp(&{b}) != std::cmp::Ordering::Less)"),
                    _ => unreachable!(),
                }
            }
            LE::Cmp(op, a, b, t) => {
                let (a, b) = (self.e(a), self.e(b));
                let sym = match op {
                    Op::Eq => "==",
                    Op::Ne => "!=",
                    Op::Lt => "<",
                    Op::Le => "<=",
                    Op::Gt => ">",
                    Op::Ge => ">=",
                    Op::And => "&&",
                    Op::Or => "||",
                    _ => unreachable!(),
                };
                if *t == LTy::PInt {
                    return format!("(({a}).cmp(&{b}) {sym} std::cmp::Ordering::Equal)");
                }
                format!("(({a}) {sym} ({b}))")
            }
            LE::Neg(x, ovf) => match ovf {
                Ovf::Panic(l) => format!("neg({}, {})", self.e(x), loc(l)),
                _ => format!("({}).wrapping_neg()", self.e(x)),
            },
            LE::Not(x) => format!("(!{})", self.e(x)),
            LE::Cond(c, a, b) => format!("(if {} {{ {} }} else {{ {} }})", self.e(c), self.e(a), self.e(b)),
            LE::Call(f, args) => format!("{f}({})", args.iter().map(|x| self.e(x)).collect::<Vec<_>>().join(", ")),
            LE::Rt(rt, args) => {
                let a: Vec<String> = args.iter().map(|x| self.e(x)).collect();
                let p0 = args.first().map(|x| self.place(x)).unwrap_or_default();
                let call = |f: &str| format!("{f}({})", a.join(", "));
                match rt {
                    Rt::IntToS => call("int_to_s"),
                    Rt::PIntToS => format!("({}).to_s()", a[0]),
                    Rt::StrRev => call("str_rev"),
                    Rt::StrDelete => call("str_delete"),
                    Rt::StrSplit => call("str_split"),
                    Rt::StrToI => call("str_to_i"),
                    Rt::StrChar => format!("str_charlen(&{p0}, {})", a[1]),
                    Rt::StrByte => {
                        if a[2] == "(0i64)" {
                            format!("str_byte(&{p0}, {})", a[1])
                        } else {
                            format!("str_sub(&{p0}, {}, {})", a[1], a[2])
                        }
                    }
                    Rt::StrLen => format!("{p0}.len()"),
                    Rt::NDigits => format!("{}.len()", call("int_to_s")),
                    Rt::PNDigits => format!("({}).to_s().len()", a[0]),
                    Rt::Isqrt => call("isqrt"),
                    Rt::Digits => call("digits"),
                    Rt::PDigits => format!("({}).digits({})", a[0], a[1]),
                    Rt::SatAdd => call("sat_add"),
                    Rt::ArrCopy => a[0].clone(),
                    Rt::Even => call("even"),
                    Rt::PEven => format!("({}).even()", a[0]),
                    Rt::PToI64 => format!("({}).to_i64({})", a[0], a[1]),
                    Rt::IntToF => format!("(({}) as f64)", a[0]),
                    Rt::FToI => call("f_to_i"),
                    Rt::FSqrt => format!("({}).sqrt()", a[0]),
                    Rt::FAbs => format!("({}).abs()", a[0]),
                    Rt::FToS => call("f_to_s"),
                    Rt::FFmt => call("f_fmt"),
                    Rt::StrCat => format!("str_cat(vec![{}])", a.join(", ")),
                    Rt::U64ToS => format!("Str::lit((({}) as u64).to_string().as_bytes())", a[0]),
                    Rt::IntFmt => call("int_fmt"),
                    Rt::FToU64 => call("f_to_u64"),
                    Rt::RuneToS => call("rune_to_s"),
                }
            }
            LE::Index { arr, idx, check } => {
                let p = self.place(arr);
                let i = self.e(idx);
                match check {
                    Some(l) => format!("{p}[idx({i}, {p}.len(), {})].clone()", loc(l)),
                    None => format!("{p}[({i}) as usize].clone()"),
                }
            }
            LE::Len(x) => format!("({}.len() as i64)", self.place(x)),
            LE::ArrLit(_, vs) => format!("vec![{}]", vs.iter().map(|x| self.e(x)).collect::<Vec<_>>().join(", ")),
            LE::ArrNew(_, n, fill, l) => format!("arr_new({}, {}, {})", self.e(n), self.e(fill), loc(l)),
            LE::ArrWithCap(_, n) => format!("Vec::with_capacity(cap({}))", self.e(n)),
            LE::Slice(_, a, start, len) => {
                let p = self.place(a);
                let (s, n) = (self.e(start), self.e(len));
                format!("{p}[({s}) as usize..(({s}) + ({n})) as usize].to_vec()")
            }
            LE::Range(lo, hi, ex) => format!("AlxRange {{ lo: {}, hi: {}, excl: {ex} }}", self.e(lo), self.e(hi)),
            LE::RangeField(r, k) => format!("{}.{}", self.place(r), ["lo", "hi", "excl"][*k as usize]),
            LE::GenNew(id, vals) => format!("gen_new_{id}({})", vals.iter().map(|x| self.e(x)).collect::<Vec<_>>().join(", ")),
            LE::ToP(x) => format!("PInt::from_i64({})", self.e(x)),
        }
    }
}
