#!/usr/bin/env python3
"""Instantiates sort.tmpl (the sorting kernels) as alexandrite source.

  slices/sort_kernels.alx   ordered (`<`) and cmp-function (`_func`) variants
  sort/sort_kernels.alx     less-function (`_less`) variant, for sort.slice

Run from anywhere: python3 std/slices/gen_sort.py
"""
import os
import re

here = os.path.dirname(os.path.abspath(__file__))
tmpl = open(os.path.join(here, "sort.tmpl")).read()

VARIANTS = {
    "ord": dict(S="", P="", A="", lt=lambda a, b: f"({a} < {b})"),
    "func": dict(S="_func", P=", cmp: (T, T) -> Int", A=", cmp", lt=lambda a, b: f"(cmp({a}, {b}) < 0)"),
    "less": dict(S="_less", P=", less: (T, T) -> Bool", A=", less", lt=lambda a, b: f"less({a}, {b})"),
}


def inst(v):
    s = tmpl
    # drop the template's own header comment
    s = s.split("\n\n", 1)[1]
    s = re.sub(r"LT\(([^,()]+(?:\[[^\]]*\])?),\s*([^,()]+(?:\[[^\]]*\])?)\)", lambda m: v["lt"](m.group(1).strip(), m.group(2).strip()), s)
    for k in ("S", "P", "A"):
        s = s.replace("{" + k + "}", v[k])
    assert "LT(" not in s, "unexpanded LT"
    return s


def emit(path, names, note):
    body = "".join(inst(VARIANTS[n]) + "\n" for n in names)
    hdr = f"# GENERATED by std/slices/gen_sort.py from sort.tmpl; do not edit.\n# {note}\n\n"
    open(os.path.join(here, "..", path), "w").write(hdr + body.rstrip("\n") + "\n")


emit("slices/sort_kernels.alx", ["ord", "func"], "Sorting kernels: ordered and cmp-function variants.")
emit("sort/sort_kernels.alx", ["less"], "Sorting kernels: less-function variant.")
