[package]
name = "alx-web"
version = "0.1.0"
edition.workspace = true
license.workspace = true
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
alx = { path = "../compiler" }
wasm-bindgen = "=0.2.129"
wasm-encoder = "0.260"
num-bigint = "0.4"
num-traits = "0.2"
num-integer = "0.1"
libm = "0.2"
